name: Twilio Call Scheduler

on:
  workflow_dispatch: # allows manual trigger from Actions tab
  push:
    branches:
      - main
  schedule:
    - cron: "55 15 * * 2" # Every Tuesday 3:55 PM UTC (9:25 PM IST)

jobs:
  make-call:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script to make a call
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
          MY_PHONE_NUMBER: ${{ secrets.MY_PHONE_NUMBER }}
          TWIML_BIN_URL: ${{ secrets.TWIML_BIN_URL }}
        run: python call.py
