name: Twilio Call Scheduler

on:
  schedule:
    - cron: "*/2 * * * *" # Every even minute (UTC)
  workflow_dispatch: # allow manual trigger

jobs:
  make-call:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: |
          python -m pip install --upgrade pip
          pip install twilio python-dotenv

      - run: python call.py
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
          TO_NUMBER: ${{ secrets.TO_NUMBER }}
